"""empty message

Revision ID: 10f47b8c2d98
Revises: ea75d3e311d8
Create Date: 2026-03-11 18:28:34.952820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f47b8c2d98'
down_revision: Union[str, Sequence[str], None] = 'ea75d3e311d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_assets', sa.Column('video_prompt', sa.Text(), nullable=True))
    op.drop_column('campaign_assets', 'video_duration')
    op.drop_column('campaign_assets', 'video_storyboard')
    op.add_column('video_versions', sa.Column('prompt', sa.Text(), nullable=True))
    op.drop_column('video_versions', 'video_storyboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_versions', sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('video_versions', 'prompt')
    op.add_column('campaign_assets', sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('campaign_assets', sa.Column('video_duration', sa.INTEGER(), server_default=sa.text('8'), autoincrement=False, nullable=True))
    op.drop_column('campaign_assets', 'video_prompt')
    # ### end Alembic commands ###
