"""empty message

Revision ID: 3b30e2e01b14
Revises: 10f47b8c2d98
Create Date: 2026-03-12 14:15:36.285205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b30e2e01b14'
down_revision: Union[str, Sequence[str], None] = '10f47b8c2d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_assets', sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaign_assets', sa.Column('video_duration', sa.Integer(), server_default=sa.text('8'), nullable=True))
    op.drop_column('campaign_assets', 'video_prompt')
    op.add_column('video_versions', sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('video_versions', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_versions', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('video_versions', 'video_storyboard')
    op.add_column('campaign_assets', sa.Column('video_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('campaign_assets', 'video_duration')
    op.drop_column('campaign_assets', 'video_storyboard')
    # ### end Alembic commands ###
