"""empty message

Revision ID: 6f33df4221f1
Revises: 885575dc018e
Create Date: 2026-04-16 15:12:45.216855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f33df4221f1'
down_revision: Union[str, Sequence[str], None] = '885575dc018e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('event_angle', sa.String(), nullable=True))
    op.add_column('video_assets', sa.Column('event_angle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_assets', 'event_angle')
    op.drop_column('image_assets', 'event_angle')
    # ### end Alembic commands ###
