"""empty message

Revision ID: 885575dc018e
Revises: c705edc9394a
Create Date: 2026-04-16 02:07:00.697975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885575dc018e'
down_revision: Union[str, Sequence[str], None] = 'c705edc9394a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('event_name', sa.String(), nullable=True))
    op.add_column('video_assets', sa.Column('event_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_assets', 'event_name')
    op.drop_column('image_assets', 'event_name')
    # ### end Alembic commands ###
