"""empty message

Revision ID: bbfc89b46a0e
Revises: e8e8483de39d
Create Date: 2026-03-17 17:39:16.866344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbfc89b46a0e'
down_revision: Union[str, Sequence[str], None] = 'e8e8483de39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['campaign_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_assets_id'), 'image_assets', ['id'], unique=False)
    op.create_table('video_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['campaign_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_id'), 'video_assets', ['id'], unique=False)
    op.drop_index(op.f('ix_video_versions_id'), table_name='video_versions')
    op.drop_table('video_versions')
    op.drop_index(op.f('ix_image_versions_id'), table_name='image_versions')
    op.drop_table('image_versions')
    op.drop_column('campaign_assets', 'image_prompt')
    op.drop_column('campaign_assets', 'video_duration')
    op.drop_column('campaign_assets', 'video_url')
    op.drop_column('campaign_assets', 'image_url')
    op.drop_column('campaign_assets', 'video_storyboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_assets', sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('campaign_assets', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaign_assets', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaign_assets', sa.Column('video_duration', sa.INTEGER(), server_default=sa.text('8'), autoincrement=False, nullable=True))
    op.add_column('campaign_assets', sa.Column('image_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('image_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['campaign_assets.id'], name=op.f('image_versions_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('image_versions_pkey'))
    )
    op.create_index(op.f('ix_image_versions_id'), 'image_versions', ['id'], unique=False)
    op.create_table('video_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('video_storyboard', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['campaign_assets.id'], name=op.f('video_versions_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('video_versions_pkey'))
    )
    op.create_index(op.f('ix_video_versions_id'), 'video_versions', ['id'], unique=False)
    op.drop_index(op.f('ix_video_assets_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_image_assets_id'), table_name='image_assets')
    op.drop_table('image_assets')
    # ### end Alembic commands ###
