"""empty message

Revision ID: c705edc9394a
Revises: bbfc89b46a0e
Create Date: 2026-03-21 16:24:19.058824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c705edc9394a'
down_revision: Union[str, Sequence[str], None] = 'bbfc89b46a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('is_strategy_approved', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'is_strategy_approved')
    op.drop_column('campaigns', 'chat_history')
    # ### end Alembic commands ###
