"""empty message

Revision ID: e8e8483de39d
Revises: 3b30e2e01b14
Create Date: 2026-03-17 16:16:12.169457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8e8483de39d'
down_revision: Union[str, Sequence[str], None] = '3b30e2e01b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('name', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('objective', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('posting_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('campaigns', sa.Column('trending_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'trending_events')
    op.drop_column('campaigns', 'posting_strategy')
    op.drop_column('campaigns', 'objective')
    op.drop_column('campaigns', 'name')
    # ### end Alembic commands ###
