"""empty message

Revision ID: ecb041e1aed0
Revises: 5eaac9c1eda6
Create Date: 2026-04-25 20:29:35.732061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb041e1aed0'
down_revision: Union[str, Sequence[str], None] = '5eaac9c1eda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('thought_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_assets', 'thought_signature')
    # ### end Alembic commands ###
