ARABIC_COUNTRIES = {
    "السعودية": "sa", "ksa": "sa", "سعودية": "sa",
    "الامارات": "ae", "الإمارات": "ae", "دبي": "ae", "uae": "ae",
    "مصر": "eg", "egypt": "eg",
    "سوريا": "sy", "syria": "sy",
    "الاردن": "jo", "الأردن": "jo", "jordan": "jo",
    "لبنان": "lb", "lebanon": "lb",
    "الكويت": "kw", "kuwait": "kw",
    "قطر": "qa", "qatar": "qa",
    "عمان": "om", "oman": "om",
    "البحرين": "bh", "bahrain": "bh",
    "المغرب": "ma", "morocco": "ma",
    "تونس": "tn", "tunisia": "tn",
    "الجزائر": "dz", "algeria": "dz",
    "ليبيا": "ly", "libya": "ly",
    "السودان": "sd", "sudan": "sd",
    "اليمن": "ye", "yemen": "ye",
    "فلسطين": "ps", "palestine": "ps",
    "العراق": "iq", "iraq": "iq",
    "موريتانيا": "mr", "mauritania": "mr",
    "جزر القمر": "km", "comoros": "km",
    "جيبوتي": "dj", "djibouti": "dj",
    "الصومال": "so", "somalia": "so",
    "جبل طارق": "gi", "gibraltar": "gi",
    "قبرص": "cy", "cyprus": "cy",
}